#!/bin/bash

USAGE="usage: $0 N WORKERS"

if [ "$#" != 2 ]; then
	echo ${USAGE}
	exit 1
fi

N=$1
STEPS=$2
WORKERS=$3
EXE=./fib

if [ ! -f ${EXE} ]; then
	echo "Executable does not exist, building..."
	make -f Makefile
	if [ "$?" -eq 0 ]; then
		echo "Done."
	else
		echo "Build failed"
		exit 1
	fi
	echo ""
fi

export LD_LIBRARY_PATH=../../ 
export MYTH_WORKER_NUM=${WORKERS}
echo "Executing ${EXE} ${N} with ${WORKERS} workers..."
${EXE} ${N}
