#!/bin/bash

USAGE="usage: $0 WORKERS [OPTIONS]"

if [ "$#" -lt 1 ]; then
	echo ${USAGE}
	exit 1
fi

WORKERS=$1; shift
EXE=./treecode

if [ ! -f ${EXE} ]; then
	echo "Executable does not exist, building..."
	make -f Makefile
	if [ "$?" -eq 0 ]; then
		echo "Done."
	else
		echo "Build failed"
		exit 1
	fi
	echo ""
fi

export LD_LIBRARY_PATH=../../ 
export MYTH_WORKER_NUM=${WORKERS}
echo "Executing '${EXE} $*' with ${WORKERS} workers..."
${EXE} $*
